-- ⚠️ NO CORRER — SUPERSEDIDO. Ver tasks/todo.md, sección "Cajón persistente
-- en el Ledger", nota del 2026-07-07 (corrección de Javi).
--
-- Este script se escribió asumiendo que el fondo inicial de $805 nunca se
-- había registrado como cash_movement. Javi confirmó que SÍ existe: ya está
-- en `cash_movements` con categoría `aportacion_socio`, ligado al primer
-- turno que se abrió. Correr este INSERT crearía un $805 duplicado y
-- desfasaría el cajón persistente del Ledger por esa cantidad de más.
--
-- No se requiere ninguna acción — el cálculo persistente (utils/ledger.js →
-- computeRunningBalances) ya suma automáticamente cualquier cash_movement
-- existente con destination_location = 'drawer', así que ese movimiento
-- histórico ya se está contando bien sin tocar nada.
--
-- Único detalle cosmético posible (no financiero): si el `created_at` de ese
-- movimiento quedó fechado durante o después de la apertura del primer turno
-- (en vez de antes), el marcador "Apertura de turno" del turno 1 en
-- /admin/ledger podría mostrar una "diferencia vs. sistema" de $805 — es solo
-- un artefacto de orden cronológico de ESE turno histórico específico, no un
-- error real ni algo que afecte turnos actuales o futuros. Se deja como está;
-- no amerita tocar timestamps de producción por un detalle puramente visual
-- en un turno de hace meses.
--
-- Contenido original del script (NO EJECUTAR — se conserva solo como registro
-- de lo que se consideró y por qué se descartó):
--
-- INSERT INTO public.cash_movements (
--     shift_id, user_id, type, amount, note, category, movement_nature,
--     source_location, destination_location, created_at
-- )
-- SELECT
--     first_shift.id, first_admin.id, 'deposit', 805,
--     'Fondo inicial histórico — caja chica para cambio, puesta un día antes de abrir el primer turno (backfill 2026-07-07)',
--     'aportacion_socio', 'owner_funding', 'owner', 'drawer',
--     first_shift.opened_at - INTERVAL '1 day'
-- FROM
--     (SELECT id, opened_at FROM public.shifts ORDER BY opened_at ASC LIMIT 1) AS first_shift,
--     (SELECT id FROM public.users WHERE role = 'admin' ORDER BY created_at ASC LIMIT 1) AS first_admin;
